### PR TITLE
Interpret - as STDIN config file

### PR DESCRIPTION
**Pull request by bebehei**
As proposed in #357

### CODE REVIEW

**Comment by tsipinakis** [comment]
While kinda a hack, isn't this already possible by giving `/dev/stdin` as the config file?

**Comment by bebehei** [comment]
... so what's your resolution?

**Comment by tsipinakis** [comment]
> ... so what's your resolution?

I'd say this is unnecessary since there's already a working solution that resolves this usecase so I'd close this but it's up to debate.

**Comment by bebehei** [comment]
The only reason, why I want to add this, is because common unix tools interpret a single dash also as STDIN (e.g.: grep, cat, etc...). When I have to give stdin as a parameter I always want to check first, if the program is able to interpret `-`. I actually never fall back to `/dev/stdin`.

**Pull request merged**
