### PR TITLE
Add color gradients

### LINKED ISSUE #1273: Feature: Color gradient
Hello, I was fiddling around and implementing a color gradient feature.
It is still unfinished though and I would like to hear your ideas.

I wanted to add the option to have a gradient to the background and progress bar.
Basically we have a list a colors that are put in a `cairo_pattern_t`.
If there is only one color the behavior is the same as it is now.

For the syntax of I was thinking of one of the following
```ini
# separate
background = whatever # ignored
background_gradient = 0xffaa22,0xfaf2a
```

or 

```ini
background = red, green, blue
```

Example:
img-1706811365

### PR DESCRIPTION
**Pull request by bynect**
Supersedes #1286

### CODE REVIEW

**Comment by bynect** [comment]
I added the gradient only for the `highlight` at the moment, but it should be easy to add to the others. the cairo pattern is cached at the start. for the rest it is basically the same as #1286 but with a custom gradient type instead of a string list

**Comment by bynect** [comment]
this is what it looks like
img-1723929625

**Comment by bynect** [comment]
@zappolowski @fwsmit should be ready. I already closed the old pr

**Comment by bynect** [comment]
ok fixed 🤣

**Comment by bynect** [comment]
@zappolowski @fwsmit can I merge this?

**Comment by cwrau** [comment]
Amazing! Is there a timeline for when the next release will happen? 😊

**Comment by bynect** [comment]
> Amazing! Is there a timeline for when the next release will happen? 😊

We don't have a timeline but since it's been a while since the last a new release is almost ready

**Pull request merged**
