### PR TITLE
Add tests for extract_urls

### PR DESCRIPTION
**Pull request by anbenson**

### CODE REVIEW

**Comment by anbenson** [comment]
I appreciate any comments you have. In particular, I'm wondering about the following things, if you'd be willing to take the time to answer:
- My first attempt at this PR resulted in memory leaks. Ok, sure, I didn't think about freeing memory in my tests. But when I ran valgrind locally, it pointed out memory leaks in suite_icon, which TravisCI didn't seem to catch. Do you know anything about that?
- I used g_free to free the strings (which originate from a g_strconcat call, so it seems appropriate). Is there a difference from regular free()?
- Should I not be freeing the pointers which I know to be NULL in the first two tests? It'd be safe if it were normal free(), but interested in your opinion.

**Comment by tsipinakis** [comment]
Hi! Thanks for firing yet another PR. To answer your questions quickly:

> My first attempt at this PR resulted in memory leaks. Ok, sure, I didn't think about freeing memory in my tests. But when I ran valgrind locally, it pointed out memory leaks in suite_icon, which TravisCI didn't seem to catch. Do you know anything about that?

I'm not aware of that (if I was I can't seem to remember about it). Can you post the stack trace?

> I used g_free to free the strings (which originate from a g_strconcat call, so it seems appropriate). Is there a difference from regular free()?

The [glibs docs](https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html) say that `g_*` functions that allocate memory should be matched with `g_free`. A while ago we were using both `free`s interchangeably and hadn't ran into any issues but still, it's better safe than sorry as they say.

> Should I not be freeing the pointers which I know to be NULL in the first two tests? It'd be safe if it were normal free(), but interested in your opinion.

I'm not sure about that, I can come up with good arguments for both sides so I'll settle for "do as you see fit".

**Comment by bebehei** [comment]
> My first attempt at this PR resulted in memory leaks. Ok, sure, I didn't think about freeing memory in my tests. But when I ran valgrind locally, it pointed out memory leaks in suite_icon, which TravisCI didn't seem to catch. Do you know anything about that?

Well, in recent times the authors of librsvg heavily change librsvg's backend. This includes also some new memory leaks (it's heaviest incarnation #538).

I see them now for about 3 months when running the testsuite locally. As they don't appear on with Travis' old librsvg version, I just ignore them.

 We actually should fix them upstream.

**Comment by bebehei** [comment]
I had stitching eyes while reading the extract_urls function.

**Comment by anbenson** [comment]
I certainly can, but I'll have to let this PR sit for a little while as I won't have time for a bit (maybe on the weekend?)

**Comment by bebehei** [comment]
> We actually should fix them upstream.

https://gitlab.gnome.org/GNOME/librsvg/merge_requests/147

**Comment by bebehei** [comment]
> https://gitlab.gnome.org/GNOME/librsvg/merge_requests/147

And it got merged, released with a bugfix release and included in ArchLinux mirrors already :heart_eyes:

**Comment by bebehei** [comment]
Rebased, missing tests written. Reviewed. @tsipinakis it's your turn :wink:

**Pull request merged**
