### PR TITLE
Implement SVG coloring

### PR DESCRIPTION
**Pull request by UtkarshVerma**
This PR aims to solve #1076. It does so by doing a simple string substitution of 'currentColor' with the raised notification's foreground colour.

A better way would have been to let the SVG renderer (librsvg) take care of this but it [doesn't support](https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/FEATURES.md) specifying a custom 'currentColor' through the API AFAIK.

### CODE REVIEW

**Comment by fwsmit** [comment]
It seems like librsvg supports setting current color: https://gitlab.gnome.org/GNOME/librsvg/-/issues/379

**Comment by UtkarshVerma** [comment]
> It seems like librsvg supports setting current color: https://gitlab.gnome.org/GNOME/librsvg/-/issues/379

I saw that issue, but couldn't find any function in the API which allowed doing this.

**Comment by progandy** [comment]
> > It seems like librsvg supports setting current color: https://gitlab.gnome.org/GNOME/librsvg/-/issues/379
> 
> I saw that issue, but couldn't find any function in the API which allowed doing this.

I'd guess it should be something like 
```rsvg_handle_set_stylesheet(..., "svg {color: $forgegroundcolor;}", ...)```

**Comment by fwsmit** [comment]
The suggestion by progandy seems good. @UtkarshVerma, could you take a look to see if it's possible to implement it?

**Comment by fwsmit** [comment]
@UtkarshVerma It's been a while. Would you like to finish this PR?

**Comment by UtkarshVerma** [comment]
@fwsmit Unfortunately, I'm too caught up with work. It would be great if someone else picked this PR up.

**Comment by fwsmit** [comment]
Allright, let me know if anyone wants to pick this up

**Comment by UtkarshVerma** [comment]
@fwsmit I have implemented this feature. Please let me know what you think. I need your suggestions on the following:
- Can we make the SVG stylesheet user-configurable? We can make it default to `svg: { color: %s; }`, but if the user has icon-themes which don't depend on `currentColor`, then they can override it to more powerful rules like `path { fill: %s !important; }`.
- I think the SVG is being scaled differently than the PNG icons. It would be great if you could chime in on this.

**Comment by fwsmit** [comment]
Thanks for implementing!

> * Can we make the SVG stylesheet user-configurable? We can make it default to `svg: { color: %s; }`, but if the user has icon-themes which don't depend on `currentColor`, then they can override it to more powerful rules like `path { fill: %s !important; }`.

If that's neccesary, then yes. But I'd suggest to first make the simplest version of styling and later allow for more complicated configuration (while not breaking the simpler one). I think it's most valuable to have a simple way to configure the colours and only require more complicated configuration for more complicated cases.

> * I think the SVG is being scaled differently than the PNG icons. It would be great if you could chime in on this.

I did some work on the icon lookup. I explained most of it while implementing. Take a look at #992 for example.

It depends on how you pass the icon to dunst. If it's via an icon theme, the minimum and maximum size specified by the theme are used. There were bugs where SVG icons were too big, but that should be fixed with #1003 (note that the configuration is now once again using `min_icon_size` and `max_icon_size` and not `icon_size`.

If you have any specific questions, do let me know, as it's quite complicated.

**Comment by fwsmit** [comment]
We'll need to add librsvg to the docker image for the tests to work. Also, are you able to add some tests to test these changes?

**Comment by UtkarshVerma** [comment]
SVG scaling was an issue in the older code. I've fixed it for now by switching to cairo-based rendering. Time is still a constraint for me, so I would really appreciate if someone could pick up this PR and iron out the few remaining details.

**Comment by fwsmit** [comment]
> SVG scaling was an issue in the older code.

Could you elaborate on what issue there was with SVG scaling?


> Time is still a constraint for me, so I would really appreciate if someone could pick up this PR and iron out the few remaining details.

I'm not active here anymore either. So I've added the help wanted tag.

**Comment by fwsmit** [comment]
What still needs to be done? I can think of the following:

- Add librsvg to the CI images (https://github.com/dunst-project/docker-images). I'm willing to help with that.
- Add tests
- Do manual testing

If that's done, I will review the code more thoroughly. Haven't found any issues with a quick scan.

**Comment by UtkarshVerma** [comment]
You've covered pretty much everything. The other thing which is remaining is adding a configuration option for specifying the SVG stylesheet.

**Comment by bynect** [comment]
Hello, I encountered the problem of styling icons, so I am willing to pick this pr up.
If you could please specify the unfinished tasks I'll try taking care of them.

**Comment by fwsmit** [comment]
For organizational purposes I'm going to close this pull request. If you or anyone else wants to work on this, feel free to reopen this pull request or start a new one (referencing this PR).

**Pull request closed without merging**
