### PR TITLE
Allow using custom indicators for actions and URLs

### PR DESCRIPTION
**Pull request by elamperti**
This PR introduces two new settings (`action_indicator` and `url_indicator`) which could be set to any string, and then be placed wherever the user finds it useful in the `format` string (using `%A` or `%U`).

There's also the possibility to use `%D` in the format to show how many duplicates a given notification has.

I've tested this locally using emoji instead of the classic "(A)" and "(U)". It works, so it should be usable with nerd fonts and similar icon fonts too.

ℹ️  As it is now, this PR is a draft to gather feedback. Things that are still to be done or defined:

- [ ] Tests
- [ ] Should we use a single format token (e.g. `%X`) to show all possible indicators in it? (actions, URLs, duplicates)
- [ ] How could this deprecate the old implementation? (or how should they live together to avoid duplicate indicators?)
- [ ] Get feedback from other users (specially those who participated in #509)

### CODE REVIEW

**Comment by fwsmit** [comment]
Thanks for submitting this PR

> Should we use a single format token (e.g. %X) to show all possible indicators in it? (actions, URLs, duplicates)

I don't think this is necessary. If you have a use case, then I wouldn't be against it.

> How could this deprecate the old implementation? (or how should they live together to avoid duplicate indicators?)

`show_indicators` is not really useful anymore with this implementation, so it should be marked deprecated. Then we could remove it in the next major version (which will probably not come any time soon). In the mean time, `show_indicators` should just prepend `(%A%U)` or something similar to the notification text, before it's being processed by your new code. If you do that right, nothing should change for existing users, but they are able to change the indicator after that.

`hide_duplicate_count=false` should also just append `(%D)` or similar to the notification text.

**Comment by fwsmit** [comment]
Hi, have you looked at my above comment? Let's figure out together what to do to finish this PR

**Comment by elamperti** [comment]
Hi, sorry for leaving this PR hanging. I'll get back to it this week. Thank you!

**Comment by fwsmit** [comment]
Hey, thanks for your update. Let me know when you get to it!

**Comment by bynect** [comment]
It would be nice to add a format parameter for the number of actions

**Comment by fwsmit** [comment]
Yeah, that should definitely be possible

**Comment by fwsmit** [comment]
For organizational purposes I'm going to close this pull request. If you or anyone else wants to work on this, feel free to reopen this pull request or start a new one (referencing this PR).

**Comment by elamperti** [comment]
Sorry for dropping the ball. I've just opened a new PR with the missing changes + added the option to show action count using `%C`.

**Pull request closed without merging**
