### PR TITLE
per section 'frame_color' parameter

### PR DESCRIPTION
**Pull request by shizeeg**
make it possible to change frame color on section basis. For example when I receive notifications from [twitch.tv](https://twitch.tv/) I want them to be in twitch color scheme.

### CODE REVIEW

**Comment by tsipinakis** [comment]
Thanks for the contribution! Works as intended.

The manpage has been neglected lately, can you also update the `RULES` and `COLORS` section of the manpage to mention the new variable?

**Comment by shizeeg** [comment]
@tsipinakis oops, totally forget about that, done. Should I merge my pull request into one commit & reopen it?

**Comment by tsipinakis** [comment]
There is no need to reopen the PR, just squash the commits.
```
git rebase -i HEAD~2
```
Change the first word on the second commit to `fixup` (aka merge with the previous commit)

and `git push --force`

**Comment by shizeeg** [comment]
thanks for your help. Done.

**Comment by tsipinakis** [comment]
Thank you for your work.

(Not sure what's up with coveralls, it's been failing randomly lately -.- )

**Pull request merged**
