### PR TITLE
Update CI to Github actions

### PR DESCRIPTION
**Pull request by bebehei**
As discussed in #699, I've updated the CI to use github actions. It works even smoother than CircleCI. I haven't expected this.

### CODE REVIEW

**Comment by tsipinakis** [comment]
Looks like the Debian, Ubuntu, and Alpine runs [failed](https://github.com/bebehei/dunst/runs/550238401) because curl isn't included by default

**Comment by bebehei** [comment]
Yep, I pushed those changes already into the git repo.... well not. :confused: ... It was still in my local staging :see_no_evil:

**Comment by tsipinakis** [comment]
If it's done can you restart the builds in your fork? Apparently it doesn't show up here until it's merged to master.

**Comment by bebehei** [comment]
Thanks for the hint. It succeeded in my fork. I'm not sure, but I guess we have to merge it blind and preliminarily without a commit status.

Does this suffice for you? https://github.com/bebehei/dunst/runs/554651286

**Comment by tsipinakis** [comment]
Yup, looks good. Let's try it.

**Pull request merged**
