### PR TITLE
Expose do_action as a keyboard shortcut

### PR DESCRIPTION
**Pull request by Crazybus**
This exposes the same do_action that a middle mouse click does on a
notification as a keyboard shortcut.

I haven't done any C in a very very long time and I have have no idea
what I'm doing :) Everything was copy pasted from one of the existing
keyboard shortcuts and to my surprise it just worked!

### CODE REVIEW

**Comment by bebehei** [comment]
It looks nice, but I'm sad to turn your PR down. We're currently deprecating the X11 keybinding (#284). A replacement PR is aleady on its way: #651. Invoking Actions will be a major part. I haven't pushed those changes yet on the PR, but your feature 

You can expect it to be merged during the next weeks.

**Comment by Crazybus** [comment]
Awesome, I'll keep an eye on that PR!

**Comment by jialeens** [comment]
Has this request merged?

**Comment by tsipinakis** [comment]
It hasn't yet. @bebehei Ping?

**Pull request closed without merging**
