### PR TITLE
Dunst readme

### PR DESCRIPTION
**Pull request by fwSmit**
The readme is probably the first thing people see of dunst, so we should put some effort in to make it look nice. I've added some images to the readme and took some of the text from the website.
Thanks to @NNBnh and  @MCotocel for providing screenshots :)
Take a look at https://github.com/fwSmit/dunst/tree/dunst-readme for how it would look like. I'm open to suggestions for improvement.

TODO:
- [ ] Resize some of the images to make the text not look blurry.

### CODE REVIEW

**Comment by MCotocel** [comment]
The image I submitted is blurry, because of the scaling in virtual machines, but I can provide a non blurry one if you want me to

**Comment by fwSmit** [comment]
I suspect the blurriness is because the image is getting resided. I'll need to crop them again

**Review by tsipinakis — APPROVED** [review]
Looks good. One suggestion: Perhaps the screenshot from our website should be the one on the top of the README since it more closely represents the notifications.

**Comment by tsipinakis** [comment]
You're free to hit the merge button on approved PRs by the way :)

**Comment by fwSmit** [comment]
I know, but I actually wanted to fix the blurry images and maybe make another image the header. Didn't get around to it yet, so I'll do that in a separate PR :)

**Pull request merged**
