### PR TITLE
Add svg icon support

### PR DESCRIPTION
**Pull request by kingcody**
This pull request adds svg icon support through the use of `librsvg`.

If this feature is desired, I'd welcome a review of the code as I am not that expirenced with C.

### CODE REVIEW

**Comment by Anachron** [comment]
Ping, please merge this!

**Comment by mephux** [comment]
Guessing the project isn't maintained anymore. Should hand it over to someone to keep it moving.

**Comment by Narrat** [comment]
No need to guess on that topic https://github.com/knopwob/dunst/issues/228
And someone could just fork it and add those PRs that are sane.
Maybe as a intermediate solution, until upstream is back again and can merge back, or as separate project

**Comment by knopwob** [comment]
@mephux I tried to find a new maintainer for this project, but noone was interessted.

**Comment by jcf** [comment]
Can I suggest giving everyone who has previously contributed to the project write access to this repository?

Any decent looking PRs can be merged if they get a good review or two from other contributors, and when someone contributes something, they too get given write access to the repo.

That'll share the workload among a number of people, and the community can decide how to improve the project with a focus on keeping Dunst lightweight, and configurable.

**Pull request closed without merging**
