### PR TITLE
Fix logging in icon code

### PR DESCRIPTION
**Pull request by bynect**
Remove extra newlines and move a string empty upwards

### CODE REVIEW

**Review by zappolowski — APPROVED** [review]

**Comment by Rentib** [comment]
Was it expected that setting default_icon = "" uses an icon?

```
[urgency_normal]
  timeout = 10
  default_icon = ""
```

This for example still uses an icon for notifications with normal urgency.
The icon used is the default one.

**Comment by bynect** [comment]
> Was it expected that setting default_icon = "" uses an icon?
> 
> ```
> [urgency_normal]
>   timeout = 10
>   default_icon = ""
> ```
> 
> This for example still uses an icon for notifications with normal urgency. The icon used is the default one.

What do you mean it uses the default icon? Also could you please open an issue

**Comment by Rentib** [comment]
> > Was it expected that setting default_icon = "" uses an icon?
> > ```
> > [urgency_normal]
> >   timeout = 10
> >   default_icon = ""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This for example still uses an icon for notifications with normal urgency. The icon used is the default one.
> 
> What do you mean it uses the default icon? Also could you please open an issue
> 
> Also, is this something that happened after this commit?

If you specify icon_theme in configuration file, then for all notifications dunst will use an icon from the theme, unless you configure it otherwise. If you check for example Papirus icons then dunst will use emblem-information icon I think.

Example config:
```
[global]
  enable_recursive_icon_lookup = true
  icon_theme = "Adwaita, Papirus"
```

**Comment by bynect** [comment]
> > > Was it expected that setting default_icon = "" uses an icon?
> > > ```
> > > [urgency_normal]
> > >   timeout = 10
> > >   default_icon = ""
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This for example still uses an icon for notifications with normal urgency. The icon used is the default one.
> > 
> > What do you mean it uses the default icon? Also could you please open an issue
> > 
> > Also, is this something that happened after this commit?
> 
> If you specify icon_theme in configuration file, then for all notifications dunst will use an icon from the theme, unless you configure it otherwise. If you check for example Papirus icons then dunst will use emblem-information icon I think.
> 
> Example config:
> ```
> [global]
>   enable_recursive_icon_lookup = true
>   icon_theme = "Adwaita, Papirus"
> ```

I don't get this behavior. Please open an issue including your dunst version and dunstrc so that I can investigate

**Pull request merged**
