### PR TITLE
Portability fixes

### PR DESCRIPTION
**Pull request by 0-wiz-0**
These patches are from pkgsrc and increase portability of dunst to other operating systems.

### CODE REVIEW

**Comment by bynect** [comment]
Related to #1171.

For the features.h it seems like it is used just to check `__GLIBC__ ` once, so maybe we can change it so we never need it?

Similarly for the button codes, I think we can remove the reliance on linux codes and just define an enum. (since they are arbitrary number anyway and are not used nowhere else)
What do you think?@fwsmit

**Comment by fwsmit** [comment]
What operating systems are you trying to port to? That would be good to know.
The button codes are plain numbers, but we get them from wayland / X11 I believe. So we need to use those specific numbers. I didn't check it though

**Comment by 0-wiz-0** [comment]
pkgsrc is cross-platform.
The evdev patches are needed at least on NetBSD, and the find patch is (I think) needed on Solaris/Illumos.

**Comment by bynect** [comment]
I resolved a conflict with #1290.
Also thanks for the pr, I'll merge it 👍🏻

**Pull request merged**
