### PR TITLE
Add tests for NotificationListHistory

### PR DESCRIPTION
**Pull request by zappolowski**
... and while at it also fix all memory leaks from this method.

### CODE REVIEW

**Comment by fwsmit** [comment]
Could you explain the memory leak?

**Comment by zappolowski** [comment]
From what I've seen it comes from `g_variant_new_from_bytes` (which is not necessary here and can be avoided by using typed versions like I did) and `g_variant_type_new`, which even states, that it transfers ownership and thus should be freed.

**Comment by zappolowski** [comment]
I've added some minor clean up:
* avoid heap allocation of the outer `builder` - just leave it on the stack as management is easier this way
* inline `answer` just for conciseness - `g_dbus_method_invocation_return_value` takes care of the floating variant created by `g_variant_new` already

PS: I cannot reproduce the pipeline failure. That image ran successfully on my machine.

**Comment by bynect** [comment]
looks good. Are you done with the changes or something is still pending?

Also friso is away at the moment

**Pull request merged**
