### PR TITLE
Allow multiple value for `-config` option

### PR DESCRIPTION
**Pull request by bynect**
This pr adds the ability to accept multiple paths for the -config option and also to handle directory paths.

Directories are simply scanned for drop-ins and if there is a dunstrc file it is loaded. Only the first dunstrc is loaded (for directories), unless the user purposefully specified multiple dunstrc in -config. 

I updated the tests and did some manual testing and so far it seems to work nicely.
This may be useful to resolve problems like that in #1207, where we want to load drop-ins and config from different directories.

### CODE REVIEW

**Comment by fwsmit** [comment]
If I read the issue right, they don't need the option to add more items to the -config option, but only that dunst scans the ~/.config/dunstrc.d/*.conf files from the home directory, even if the ~/.config/dunstrc is not present. That seems like a simpler solution.
You could also just use /etc/dunstrc.d/*.conf or an empty ~/.config/dunstrc.

**Comment by bynect** [comment]
> If I read the issue right, they don't need the option to add more items to the -config option, but only that dunst scans the ~/.config/dunstrc.d/*.conf files from the home directory, even if the ~/.config/dunstrc is not present. That seems like a simpler solution.
> You could also just use /etc/dunstrc.d/*.conf or an empty ~/.config/dunstrc.

Yes, I proposed this pr for providing a more general solution for people that (for testing or whatever) want to split their config files on different directories. Even if the other solution is easier, the difference in code would be not that much, so adding this should be worthwhile (since I already wrote it also 😁)

**Comment by fwsmit** [comment]
> > If I read the issue right, they don't need the option to add more items to the -config option, but only that dunst scans the ~/.config/dunstrc.d/_.conf files from the home directory, even if the ~/.config/dunstrc is not present. That seems like a simpler solution.
> > You could also just use /etc/dunstrc.d/_.conf or an empty ~/.config/dunstrc.
> 
> Yes, I proposed this pr for providing a more general solution for people that (for testing or whatever) want to split their config files on different directories. 

I haven't seen this in other tools, so it seems to not be a standard thing people want.

> Even if the other solution is easier, the difference in code would be not that much, so adding this should be worthwhile (since I already wrote it also 😁)

I get that you already put the effort in this code, but it's also a command line option that dunst needs to maintain indefinitely. So it can add some maintenance burden. That's why I lean more towards simpler options

**Comment by bynect** [comment]
> > > If I read the issue right, they don't need the option to add more items to the -config option, but only that dunst scans the ~/.config/dunstrc.d/_.conf files from the home directory, even if the ~/.config/dunstrc is not present. That seems like a simpler solution.
> > > You could also just use /etc/dunstrc.d/_.conf or an empty ~/.config/dunstrc.
> > 
> > Yes, I proposed this pr for providing a more general solution for people that (for testing or whatever) want to split their config files on different directories. 
> 
> I haven't seen this in other tools, so it seems to not be a standard thing people want.
> 
> > Even if the other solution is easier, the difference in code would be not that much, so adding this should be worthwhile (since I already wrote it also 😁)
> 
> I get that you already put the effort in this code, but it's also a command line option that dunst needs to maintain indefinitely. So it can add some maintenance burden. That's why I lean more towards simpler options

From what I know a lot of tool allow specifying more than one config file (either with cli options or imports in the files or etc). If you don't like the list method it could be changed to a multiple config options, like

```
Dunst -config A,B,C
# to
Dunst -config A -config B -config C
```

But this is just a way to do this so let me know if you know a better method

**Comment by bynect** [comment]
I'm going to close this, maybe I'll come up with some tweaks in the future

**Pull request closed without merging**
