### PR TITLE
[WIP] Draw tests

### PR DESCRIPTION
**Pull request by tsipinakis**
(The start of) An attempt at implementing tests for `draw.c`. I have no clue if this is going to work at all but creating a PR anyway since I'm trying to decide how to move forward and would love some feedback.

### CODE REVIEW

**Comment by bebehei** [comment]
Question: Have you evaluated Xephyr?

**Comment by bebehei** [comment]
Yes, that's right. Xephyr was the wrong hint. But I think xvfb might be the right choice. I've read through the wikipedia page. Looks pormising. Although wikipedia states, that it got "slated" in 2016 (which I can't find any info on the referred citation).

Nevertheless, there's https://xpra.org/trac/wiki/Xdummy, which claims to get an X server as a non-root user with this command: `Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./10.log -config ./xorg.conf :10`.

Just by the command invocation, I imply that it may even have randr support, so we could our screens section with this, too :grin: 

However, I haven't got enough knowledge and details to decide on spawning an X testserver vs writing a dummy output.

**Comment by bebehei** [comment]
Any progress on this?

**Comment by tsipinakis** [comment]
No, dind't get time to look enough into it but I did figure out what's the next hurdle: Pango. We depend on a lot of pango calls in draw.c and we need to figure out if the results are deterministic(read "pixel perfect") or can they change slightly. Even 1 pixel off would break the tests the way I envision it.

**Comment by tsipinakis** [comment]
Uh, I accidentally deleted the branch while cleaning up my fork and github closed this automatically. Guess it's for the best since I don't know if this will ever be done.

**Pull request closed without merging**
