### PR TITLE
Corners patch part 1

### PR DESCRIPTION
**Pull request by bynect**
I divided the patch in #1213 to simplify things a bit. This first part only deals with the rendering of the corners. The second part (which I will add soon) adds support for the customization option to change corner profile. Anyway, refer to #1213 for any information on the changes.

### CODE REVIEW

**Comment by bynect** [comment]
Should I close the other?

**Comment by fwsmit** [comment]
> Should I close the other?

No that's not neccesary

**Comment by fwsmit** [comment]
Sorry that I've taken so long to review this. This PR still contains more than just the fix for the progress bar rendering, but I'll try to roll with it. Could you explain how the bug happened in the old progress bar implementation? Good testing is nice, but it's also good to know what went wrong.

**Comment by fwsmit** [comment]
The code does look good, but I'll have to take a closer later.

**Comment by bynect** [comment]
> Sorry that I've taken so long to review this. This PR still contains more than just the fix for the progress bar rendering, but I'll try to roll with it. Could you explain how the bug happened in the old progress bar implementation? Good testing is nice, but it's also good to know what went wrong.

To bw fair, the only thing that is not about corners is the bar adjustment, which is minimal and I already commented in the original pr. (It just deals with either a pango antialiasing/number rounding issue that makes the lines slightly skewed)

When you merge this I can make the part 2 of the pr for costumizing corners

**Comment by bynect** [comment]
did you manage to see it?

> The code does look good, but I'll have to take a closer later.

**Comment by fwsmit** [comment]
Thanks for the poke. The code looks good, I haven't found any issues with it. Thanks for your patience and working on this fix. I will go ahead and merge this. I look forward to the V2 patch!

**Comment by bynect** [comment]
Thanks. I'll prepare the patch as soon as I have a little spare time since the code is already there. Sometime next week at most

**Pull request merged**
