### PR TITLE
Fix coverage for forks

### PR DESCRIPTION
**Pull request by bynect**
fix #1327

### CODE REVIEW

**Comment by bynect** [comment]
My bad, I just realized that it's all the workflows and not just coverage that runs on my fork

**Comment by bynect** [comment]
image

**Comment by zappolowski** [comment]
The error you're encountering is due to missing git tags. As `git describe --tags` is used to create `VERSION`, this falls back to `VERSION := "1.10.0-non-git"` which then makes the tests fail.

Short: Also fork the tags from the main repository and you're good.

**Comment by bynect** [comment]
> The error you're encountering is due to missing git tags. As `git describe --tags` is used to create `VERSION`, this falls back to `VERSION := "1.10.0-non-git"` which then makes the tests fail.
> 
> Short: Also fork the tags from the main repository and you're good.

But before this didn't cause any issue

**Pull request closed without merging**
